version: '3.1'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    networks:
      - local-network
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
networks:
  local-network:
